### ISSUE TITLE
first launch of the latest version (1.3) on psp takes about 5 minutes

### ISSUE THREAD

**Issue by Mamsikas** [CrossCraft/CrossCraft-Classic#101]
the first launch of the latest version (1.3) on psp takes about 5 minutes, although even the first time st4 starts in a few seconds

**Comment by IridescentRose** [comment]
You probably didn't extract the ZIP file on first run -- this causes the major slowdown.

**Comment by Mamsikas** [comment]
> You probably didn't extract the ZIP file on first run -- this causes the major slowdown.

I tried to extract the archive, but it did it again.  

For some reason this problem is not in st (I didn't even extract it)
