### ISSUE TITLE
coordinates and fps are a few pixels higher

### ISSUE THREAD

**Issue by Mamsikas** [CrossCraft/CrossCraft-Classic#103]
the value of the coordinates and fps are a few pixels higher than they should (in older versions this was not the case)

![bandicam 2022-12-03 16-36-36-685](https://user-images.githubusercontent.com/91743262/205434452-ccaf06c7-0bc4-4396-af3c-e08bc3ffdae3.jpg)
psp too
![image](https://user-images.githubusercontent.com/91743262/205434463-ccfa35c8-6eed-47e1-97f0-6c278a3baa91.png)
for comparison 1.2.1
![bandicam 2022-12-03 16-43-12-781](https://user-images.githubusercontent.com/91743262/205434586-5c20d57b-e337-411a-b602-0a72216c8617.jpg)

**Comment by IridescentRose** [comment]
This is literally not a bug.
