### ISSUE TITLE
<3ds> my game tells me to install base layer

### ISSUE THREAD

**Issue by Linkdash2019** [CrossCraft/CrossCraft-Classic#117]

**Comment by Linkdash2019** [comment]
Install base layer I mean

**Comment by IridescentRose** [comment]
No, it doesn't -- it's just a log. You're likely just crashing because you don't have the Crosscraft folder on your SDMC.

**Comment by Linkdash2019** [comment]
It is there though!

**Comment by Linkdash2019** [comment]
Does the 3dsx need to be on root?

**Comment by Linkdash2019** [comment]
The folder AND the 3dsx file need to be on root I figured out
