### ISSUE TITLE
3DS port crashes on startup when installed from Universal-DB

### ISSUE THREAD

**Issue by MisterSheeple** [CrossCraft/CrossCraft-Classic#118]
I installed it through Universal Updater, it only kept the 3dsx file, and not the folder with assets, causing the game to crash on start. This is a misconfiguration on the end of whoever added it to Universal-DB and should be corrected.

**Comment by KyleKart** [comment]
Well, I was digging and found the folder for the game. But the thing I am struggling to find is the game itself.

**Comment by IridescentRose** [comment]
We didn't upload this on Universal DB nor do we maintain it -- it is not our responsibility.
