### ISSUE TITLE
Graphical glith while destroying blocks

### ISSUE THREAD

**Issue by TheESN** [CrossCraft/CrossCraft-Classic#48]
There happens a small grahical glitch for a short period of time in the moment when block is destroyed

Example

https://www.youtube.com/watch?v=VZWsCQY6_r0

**Comment by IridescentRose** [comment]
I actually can't tell what the glitch is from the video? Is it a small flicker when the block is updated? If so - that is normal on platforms like the PSP with slower chunk rebuilding.

**Comment by TheESN** [comment]
> 

Yes I meant that small flicker
