### ISSUE TITLE
Small parts of near textures appear when crossed block is held in hand

### ISSUE THREAD

**Issue by TheESN** [CrossCraft/CrossCraft-Classic#49]
![IMG_20220604_124748](https://user-images.githubusercontent.com/102585253/171982089-f9f39cae-2c16-4bc6-bc02-14c98274d30d.jpg)

Here you can see a blue line on the left of sapling. Similar things happen with other blocks of this kind (Yellow flower is an exception, or I don't see it :P)

**Comment by IridescentRose** [comment]
May be a precision issue with floating point rounding errors... I'll see if it can be changed, likely can't be fixed.
