### ISSUE TITLE
how to open crosscraft on linux ubuntu?

### ISSUE THREAD

**Issue by AlekseyFOX** [CrossCraft/CrossCraft-Classic#64]
I wanted to try to download crosscraft on my PC and ran into a problem. I can't open crosscraft
I want an answer to my problem
thanks in advance.

**Comment by IridescentRose** [comment]
You need to specify much more than "I ran into a problem". What message do you get?

**Comment by AlekseyFOX** [comment]
> Вам нужно указать гораздо больше, чем "я столкнулся с проблемой". Какое сообщение вы получаете?

https://youtu.be/0yobrljoXyg
everything is shown in that video.

**Comment by IridescentRose** [comment]
You literally didn't extract it.

**Comment by AlekseyFOX** [comment]
> Вы буквально не извлекали его.

can you tell me how to extract it?

**Comment by BCDeshiG** [comment]
Usually you'd right click on the zip file and press `Extract Here`.
