### ISSUE TITLE
Cannot jump up to block if colliding with its face

### ISSUE THREAD

**Issue by MotoLegacy** [CrossCraft/CrossCraft-Classic#67]
~~To reproduce:~~
~~* Place a block~~
~~* Attempt to jump on top of block, you will only be able to approach it from a corner vertex~~
Ignore above, incorrect description. Touching a block's side face prevents you from jumping high enough to land on top of it.

**Comment by IridescentRose** [comment]
It's actually caused by velocity being set to 0 mid air.
