### ISSUE TITLE
OpenGL failed to initialize on Linux

### ISSUE THREAD

**Issue by SpidFightFR** [CrossCraft/CrossCraft-Classic#75]
When i try to launch the game, i get this error:

<details><summary>Launching error</summary>

```
[CORE][INFO]: Initialized base layer!
[CORE][ERROR]: OpenGL Init Failed!
core dumped

```
</details>

Although opengl works, either with Minecraft or with GlxGears.
How can i solve this issue, please ?

**Comment by IridescentRose** [comment]
CrossCraft and all Stardust-Celeste titles require and utilize features of OpenGL 4.0 -- can you verify that your supported OpenGL version is at least 4.0?

**Comment by SpidFightFR** [comment]
hello @IridescentRose, thank you for your response.
I think the problem relies on the version of OpenGL i use.

When i run `glxinfo | grep OpenGL`, i get this line (among others):

`OpenGL version string: 3.0 Mesa 22.1.4`

I'll try to search for a way to install OpenGL 4.0 or up.

**Comment by SpidFightFR** [comment]
After investigation, i found out that you can change the OpenGL version available in the mesa drivers by adding the two environment `MESA_GL_VERSION_OVERRIDE=4.5` and `MESA_GLSL_VERSION_OVERRIDE=450`

These variables are for developing purposes only and can be very unstable.
If you wanna run the game with those variables, try this command (in the game folder):
`MESA_GL_VERSION_OVERRIDE=4.5 MESA_GLSL_VERSION_OVERRIDE=450 ./Crosscraft-Classic`

This solves the issue.

(now i have another issue regarding texture packs i think...)

<details><summary>Texture pack error</summary>

```
[CORE][INFO]: Initialized base layer!
[APP][INFO]: TEXTURE PACK INFO:
[CORE][DEBUG]: Added Controller!
[CORE][DEBUG]: Added Controller!
[CORE][DEBUG]: Added Controller!
[CORE][DEBUG]: Added Controller!
Segmentation error (core dumped)
```

</details>

But that's another issue, the OpenGL issue is fixed. thank you all for your help.
