### ISSUE TITLE
Cursor doesn't disappear after pressing "back to game" in pause menu

### ISSUE THREAD

**Issue by TheESN** [CrossCraft/CrossCraft-Classic#82]
At least it happens in Windows

**Comment by IridescentRose** [comment]
Haven't been able to confirm this on Windows

**Comment by BCDeshiG** [comment]
Funnily enough I had it happen to me on Linux though I wasn't able to reproduce it again afterwards.

**Comment by IridescentRose** [comment]
Hm, seems like there's more advanced behavior behind why this occurs then.

**Comment by IridescentRose** [comment]
I think I've found the reason -- back to game doesn't call PauseMenu::exit which restores cursor behavior. Should be a simple patch

**Comment by IridescentRose** [comment]
Fixed and will be backported in v1.3
