### ISSUE TITLE
You are joined in another session

### ISSUE THREAD

**Issue by Leleuxx** [CrossCraft/CrossCraft-Classic#83]
hello, a bug is happening for me from time to time, my game closes by itself and when I open it again it appears: "you are joined in another session" It happened twice, the first was yesterday and the other just now. The first time I had to reinstall and now it's back to normal by itself. I play on a psp 3000

**Comment by MotoLegacy** [comment]
This is because the server does not have a user timeout function, and since the game unexpectedly crashes the player is still present. Either ask a server operator to kick an old player or re-join with a new username.
