### ISSUE TITLE
Vita Crashes Black Screen

### ISSUE THREAD

**Issue by Antonnnnnnnnnnnnnnnnnnnn** [CrossCraft/CrossCraft-Classic#85]

**Comment by IridescentRose** [comment]
Next time, put your details in your question. Have you tried 1.2.1?

**Comment by IridescentRose** [comment]
Original Text:

```For some reason when i try running crosscraft classic on my vita, I just have a black screen and after 20 seconds it just crashes.. I've tried downloading from github, easyvpk, vita homebrew browser and all of them had the same result. Does Anybody know how to fix that?```

**Comment by IridescentRose** [comment]
Is libshacccg.suprx installed?

**Comment by IridescentRose** [comment]
Seems like this happens in v1.2 but not v1.2.1. Closing until further notice
