### ISSUE TITLE
I can't break blocks as fast as in the original game

### ISSUE THREAD

**Issue by Mamsikas** [CrossCraft/CrossCraft-Classic#93]
https://user-images.githubusercontent.com/91743262/186229246-b73acc55-d058-42ba-989b-b6b29e938a7c.mp4

https://user-images.githubusercontent.com/91743262/186229259-9bb3235c-ff0c-4b6d-b008-291195227ab4.mp4

**Comment by IridescentRose** [comment]
There's a limit speed. This likely will not be changed.
