### ISSUE TITLE
How can i run this project on MacOS?

### ISSUE THREAD

**Issue by Inzupera** [CrossCraft/CrossCraft-Classic#96]
and how tag issues

**Comment by Mantas22XYT** [comment]
https://github.com/CrossCraft/CrossCraft-Classic/releases/download/v1.2.1/CrossCraft-Mac.zip

**Comment by Inzupera** [comment]
> https://github.com/CrossCraft/CrossCraft-Classic/releases/download/v1.2.1/CrossCraft-Mac.zip

what i supossed to do after extract the file

**Comment by IridescentRose** [comment]
Run the executable included.

**Comment by Inzupera** [comment]
> Run the executable included.

I dont want to annoy, but i cant run it because the macs cant run that































































































































































maybe?

**Comment by IridescentRose** [comment]
Terminal cd to folder, chmod +x CrossCraft-Classic, ./CrossCraft-Classic
